version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: unit tests
          command: docker run -w $PWD -v $PWD:$PWD --entrypoint sh sparkprime/jsonnet tests.sh
      - run:
          name: start grafana
          command: docker run -d -v $PWD:$PWD -e GF_DASHBOARDS_JSON_ENABLED=true -e GF_DASHBOARDS_JSON_PATH=$PWD/tests --name=grafana -p 3000:3000 grafana/grafana
      - run:
          name: sleep
          command: sleep 10
      - run:
          name: debug
          command: docker logs grafana
      - run:
          name: acceptance tests
          command: docker run -u $UID --rm -w $PWD -v $PWD:$PWD --network=container:grafana circleci/python:2.7-browsers bash acceptance.sh
